export default {
  waterfall: require("../assets/audio/waterfall.mp3"),
  forest_stream: require("../assets/audio/forest_stream.mp3"),
  beach: require("../assets/audio/beach.mp3"),
  rainforest: require("../assets/audio/rainforest.mp3"),
  arabic: require("../assets/audio/arabic.mp3"),
  tibet: require("../assets/audio/tibet.mp3"),
  japan: require("../assets/audio/japan.mp3"),
  africa: require("../assets/audio/africa.mp3"),
  thunderstorm: require("../assets/audio/thunderstorm.mp3"),
  frequency: require("../assets/audio/frequency.mp3"),
  deep_atonal: require("../assets/audio/deep-atonal.mp3"),
  three_prayers: require("../assets/audio/prayer1.mp3"),
  autumn_sky: require("../assets/audio/autumn-sky.mp3"),
};
